packages:
  - 'apps/*'
  - 'libs/*'
allowBuilds:
  '@nestjs/core': true
  '@parcel/watcher': true
  '@scarf/scarf': set this to true or false
  '@swc/core': true
  bcrypt: true
  sharp: false
  unrs-resolver: true
